// ##########################################################################
// ### This file is generated by Build and Continuous Integration scripts ###
// ###   .github/workflows/buildinfo.py for local development environment ###
// ###   .github/workflows/testbuildrelease.yml for CI environment        ###
// ### Changes will be overwritten on the next build                      ###
// ##########################################################################

#include "buildinfo.h"

const buildEnvironment buildInfo::theBuildEnvironment{buildEnvironment::local};
const buildType buildInfo::theBuildType{buildType::development};
const int buildInfo::mainVersionDigit   = 0;
const int buildInfo::minorVersionDigit  = 0;
<<<<<<< HEAD
const int buildInfo::patchVersionDigit  = 0;
const char* buildInfo::lastCommitTag    = "55ecce4";
const char* buildInfo::buildTimeStamp   = "2023-Dec-02 22:10:51";
=======
const int buildInfo::patchVersionDigit  = 2;
const char* buildInfo::lastCommitTag    = "e99f332";
const char* buildInfo::buildTimeStamp   = "2025-Jun-06 14:48:28";
>>>>>>> f5c7f4768e459eb5a074e90aca83587b847b2121
